Repository eidoo/hybrid-exchange-sdk, pull requests merged in 2019-02, with the labels that each got.

#16 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: enhancement

#14 13 withdraw commands
  CHANGELOG.md
  src/cli/tws/withdraw.js
  src/commands/ABaseCommand.js
  src/commands/CreateWalletCommand.js
  src/commands/GetAddressCommand.js
  src/commands/OrderSignCommand.js
  src/commands/WithdrawCommand.js
  src/commands/commandList.js
  src/factories/BaseTransactionBuilder.js
  src/factories/TradingWalletTransactionBuilder.js
  src/lib/TransactionLib/TransactionLib.js
  src/models/Transaction.js
  src/validators/PrivateKeyValidator.js
  src/validators/WithdrawCommandValidator.js
  tests/unit/commands/createWalletCommand.test.js
  tests/unit/commands/signCommand.test.js
  tests/unit/commands/withdrawTokenCommand.test.js
Labels: enhancement

#23 Trading Wallet getAssetBalanceAsync refactor
  examples/lib/tradingWallet/balances/getTokenBalance.js
  src/services/TradingWalletService.js
  tests/unit/services/TradingWalletService.test.js
Labels: Refactor

#27 Add CLI Deposit ETH command
  CHANGELOG.md
  src/cli/tws/deposit-eth.js
  src/commands/DepositEthCommand.js
  src/commands/commandList.js
  src/commands/index.js
  src/validators/DepositEthCommandValidator.js
  tests/unit/commands/depositEthCommand.test.js
Labels: enhancement

#33 Fix approve command tests
  CHANGELOG.md
  src/commands/ApproveCommand.js
  src/validators/ApproveCommandValidator.js
  tests/unit/commands/approveCommand.test.js
Labels: bug

#31 Add get allowance command
  CHANGELOG.md
  src/cli/tks.js
  src/cli/tks/get-allowance.js
  src/commands/GetAllowanceCommand.js
  src/commands/commandList.js
  src/validators/GetAllowanceCommandValidator.js
  tests/unit/commands/getAllowanceCommand.test.js
Labels: enhancement

#30 Add trading wallet balance command
  CHANGELOG.md
  src/cli/tws/get-balance.js
  src/commands/GetAddressCommand.js
  src/commands/GetBalanceCommand.js
  src/commands/commandList.js
  src/commands/index.js
  src/validators/GetBalanceCommandValidator.js
  tests/unit/commands/getTradingWalletBalanceCommand.test.js
Labels: enhancement

#41 Refactor adding command factories
  CHANGELOG.md
  src/commands/commandList.js
  src/factories/commands/ApproveCommandBuilder.js
  src/factories/commands/CreateWalletCommandBuilder.js
  src/factories/commands/DepositEthCommandBuilder.js
  src/factories/commands/DepositTokenCommandBuilder.js
  src/factories/commands/GetAddressCommandBuilder.js
  src/factories/commands/GetAllowanceCommandBuilder.js
  src/factories/commands/GetBalanceCommandBuilder.js
  src/factories/commands/OrderCancelCommandBuilder.js
  src/factories/commands/OrderSignCommandBuilder.js
  src/factories/commands/WithdrawCommandBuilder.js
Labels: Refactor

#49 Create order command
  CHANGELOG.md
  src/cli/order/create.js
  src/commands/commandList.js
  src/commands/order/OrderCreateCommand.js
  src/factories/commands/order/OrderCreateCommandBuilder.js
  src/validators/commands/order/OrderCreateCommandValidator.js
  tests/unit/commands/orderCreateCommand.test.js
Labels: enhancement
